### ISSUE TITLE
Feature request: coverage ignore comments

### ISSUE THREAD

**Issue by TiddoLangerak** [rpl/flow-coverage-report#107] opened 2017-08-03 10:05 UTC
Ideally I'd have a 100% flow coverage in my projects. However, this is usually not realistic, there are almost always parts of the code base that either can't be covered at all, or are extremely difficult to cover properly. As a result, we generally can't set the threshold to 100% for CI builds, we need to lower it to a somewhat arbitrary lower value. This has as the unintended side-effect that the build will now allow a non-zero percentage of unintended uncovered code as well.

It would therefore be very useful if we could somehow specify that certain parts of the code should not count towards coverage percentage, e.g. by using comments. For example:

```javascript
/* flow-coverage ignore-next-line */
const y : any; 

const z : any; // flow-coverage-ignore-line

/* flow-coverage ignore-start */
const a : any; 
const b : any;
/* flow-coverage ignore-end */
```
The tool could still warn about missing coverage, but it just wouldn't count towards to threshold.

With something like this we would be able to set the threshold as 100% and explicitly opt-out of coverage where desired. 

Would something like this be possible and desirable for this project?

**Comment by rpl** [comment] 2017-10-25 00:59
I just noticed that this is basically a dupe of #63

**Closed by rpl** 2017-10-25 00:59 UTC
Labels: state: duplicate
