### ISSUE TITLE
stdout maxBuffer exceeded

### ISSUE THREAD

**Issue by alexeygolev** [rpl/flow-coverage-report#13] opened 2016-10-25 08:36 UTC
Getting `Error while generating Flow Coverage Report: Error: stdout maxBuffer exceeded Error: stdout maxBuffer exceeded` for some reason.

node: v6.2.0
command: `node_modules/.bin/flow-coverage-report -i 'src/**/*.js' -t html -t json -t text`

**Comment by mourner** [comment] 2016-11-04 05:11
Hitting this issue as well. Here's a test case to reproduce:

```bash
# clone https://github.com/mapbox/mapbox-gl-js, then run:
flow-coverage-report -i 'js/**/*.js'
```

**Comment by ryan953** [comment] 2016-11-04 05:50
Looks like the dev/0-2-0 branch will fix this issue for `mapbox-gl-js`.

I just checkout out that branch and ran the script from within the working folder and it worked great. The commands I ran were:
```bash
git clone https://github.com/rpl/flow-coverage-report.git
cd ./flow-coverage-report
git checkout origin/dev/0-2-0
npm install
cd ..
git clone https://github.com/mapbox/mapbox-gl-js
cd mapbox-gl-js
../flow-coverage-report/bin/flow-coverage-report.js -i 'js/**/*.js'
```

**Comment by mourner** [comment] 2016-11-04 06:09
@ryan953 wonderful, looking forward to the release!

**Comment by rpl** [comment] 2016-11-05 19:14
@alexeygolev  @mourner This issue should be fixed in the released v.0.2.0

In the v.0.2.0 there is also a new `-x` command line option to specify glob patterns to be excluded, which is helpful to explicitly exclude files that are not supposed to be collected (e.g. bundled and minified files) e.g.:
```
flow-coverage-report -i 'src/**/*.js' -x 'src/test/fixtures/**' -x 'src/**/*.min.js'   
```

**Closed by rpl** 2016-11-05 19:14 UTC
